project:
  type: website
  preview:
    port: 5555
    browser: true

    
website:
  title: "Benedict's Blog"
  image: "bird.jpg"
  favicon: "bird.jpg"
  reader-mode: true
  back-to-top-navigation: true
  page-navigation: true
  twitter-card: true
  open-graph: true
  repo-actions: [edit, issue]
  search:
    location: navbar
    type: overlay

  navbar:
    background: light
    logo: "bird.jpg"
    logo-alt: "Quarto logo."
    title: false
    collapse-below: lg
    left:
      - text: "ML"
        href: "ML/index.ipynb"
      - text: "Web Development"
        href: "01_WebDevelopment.ipynb"
      - text: "Blog"
        href: "02_Resume.ipynb"
      - text: "Help"
        menu:
          - text: "Report an Issue"
            icon: "bug"
            href: "https://github.com/bthek1/benedicts_blog/issues"
          - text: "Ask a Question"
            icon: "chat-right-text"
            href: "https://github.com/bthek1/benedicts_blog/wiki"        

    tools:
      - icon: github
        href: https://github.com/bthek1/benedicts_blog.git
        aria-label: Github
      - icon: linkedin
        href: https://www.linkedin.com/in/benedict-thekkel/
        aria-label: Linkedin
      - icon: mail
        href: https://www.linkedin.com/in/benedict-thekkel/
        aria-label: Mail

  page-footer:
    center:
      - text: "About"
        href: about.qmd
      - text: "FAQ"
        href: docs/faq/index.qmd
      - text: "License"
        href: license.qmd
      - text: "Trademark"
        href: trademark.qmd
    right:
      - icon: github
        href: "https://github.com/bthek1/benedicts_blog.git"
        aria-label: Github
      - icon: linkedin
        href: "https://www.linkedin.com/in/benedict-thekkel/"
        aria-label: Linkedin
      - icon: mail
        href: "https://www.linkedin.com/in/benedict-thekkel/"
        aria-label: Mail
  comments: 
    utterances:
      repo: quarto-dev/quarto-web
        
        
  sidebar:
    title: "ML"
    style: "floating"
    collapse-level: 2
    align: left
    contents:
      - section: "ML"
        href: "00_ML.ipynb"
        contents:
        - text: "Fast AI Setup"
          href: https://bthek1.github.io/FastAISetup/
        - text: " Fast AI course"
          href: https://bthek1.github.io/fastAIcourse/
        - text: "Machine Learning course"
          href: https://bthek1.github.io/ML/
      - section: "Web Development"
        href: "00_ML.ipynb"
        contents:
        - text: "Documentation"
          href: https://bthek1.github.io/webdevelopment_doc/
        - text: "React"
          href: https://bthek1.github.io/webdevelopment_doc/React/react.html
        - text: "Django"
          href: https://bthek1.github.io/webdevelopment_doc/django.html

      
format:
  html:
    toc: true
    theme:
      light: [cosmo, theme.scss]
    code-copy: true
    code-overflow: wrap
    css: styles.css
    grid:
      sidebar-width: 250px
      body-width: 900px
      margin-width: 300px

metadata-files: [nbdev.yml]