project:
  type: website
  preview:
    port: 5555
    browser: true

    
website:
  title: "Benedict's Blog"
  image: "bird.jpg"
  favicon: "bird.jpg"
  reader-mode: true
  back-to-top-navigation: true
  page-navigation: true
  twitter-card: true
  open-graph: true
  repo-actions: [edit, issue]
  search:
    location: navbar
    type: overlay

  navbar:
    background: light
    logo: "bird.jpg"
    logo-alt: "Quarto logo."
    title: false
    collapse-below: lg
    left:
      - text: "Blog"
        href: "Index.ipynb"
      - text: "Help"
        menu:
          - text: "Report an Issue"
            icon: "bug"
            href: "https://github.com/bthek1/benedicts_blog/issues"
          - text: "Ask a Question"
            icon: "chat-right-text"
            href: "https://github.com/bthek1/benedicts_blog/wiki"        

    tools:
      - icon: github
        href: "https://github.com/bthek1/benedicts_blog.git"
        aria-label: Github
      - icon: linkedin
        href: "https://www.linkedin.com/in/benedict-thekkel/"
        aria-label: Linkedin


  page-footer:
    center:
      - text: "About"
        href: "https://bthek1.github.io/benedicts_blog/Index.html"
      - text: "FAQ"
        href: "https://bthek1.github.io/benedicts_blog/Index.html"
      - text: "License"
        href: "https://bthek1.github.io/benedicts_blog/Index.html"
      - text: "Trademark"
        href: "https://bthek1.github.io/benedicts_blog/Index.html"
        
        
    right:
      - icon: github
        href: "https://github.com/bthek1/benedicts_blog.git"
        aria-label: Github
      - icon: linkedin
        href: "https://www.linkedin.com/in/benedict-thekkel/"
        aria-label: Linkedin

  comments: 
    utterances:
      repo: quarto-dev/quarto-web
        
        
  sidebar:
    title: "ML"
    style: "floating"
    collapse-level: 2
    align: left
    contents:
      - section: "AI"
        contents:
        - text: "Fast AI Setup"
          href: https://bthek1.github.io/FastAISetup/
        - text: " Fast AI course"
          href: https://bthek1.github.io/fastAIcourse/
          
      - section: "ML"
        contents:
        - text: "Machine Learning course"
          href: https://bthek1.github.io/ML/
          
      - section: "Timeseries"    
        contents:
        - text: "Time series course"
          href: https://bthek1.github.io/TimeSeriesML/
          
      - section: "Web Development"
        contents:
        - text: "Documentation"
          href: https://bthek1.github.io/webdevelopment_doc/
        - text: "React"
          href: https://bthek1.github.io/webdevelopment_doc/React/react.html
        - text: "Django"
          href: https://bthek1.github.io/webdevelopment_doc/django.html

      
format:
  html:
    toc: true
    theme:
      light: [cosmo, theme.scss]
    code-copy: true
    code-overflow: wrap
    css: styles.css
    grid:
      sidebar-width: 250px
      body-width: 900px
      margin-width: 300px

metadata-files: [nbdev.yml]